export { default as Navbar } from './Navbar';
export { default as Home } from './Home';
export { default as LoginReg } from './LoginRegister';
export { default as Routine } from './Routine';
export { default as Routines } from './Routines';
export { default as Activities } from './Activities'
export { default as Activity } from './Activity';
export { default as Profile } from './Profile'
export { default as MyRoutines } from './MyRoutines'